/* MySQL */

-- shortest
SELECT MIN(CITY), LENGTH(CITY)
FROM STATION
GROUP BY LENGTH(CITY)
ORDER BY LENGTH(CITY)
LIMIT 1;

-- longest
SELECT MIN(CITY), LENGTH(CITY)
FROM STATION
GROUP BY LENGTH(CITY)
ORDER BY LENGTH(CITY) DESC
LIMIT 1;

/* MS SQL */

-- shortest
SELECT TOP 1 MIN(CITY), LEN(CITY)
FROM STATION
GROUP BY LEN(CITY)
ORDER BY LEN(CITY);

-- longest
SELECT TOP 1 MIN(CITY), LEN(CITY)
FROM STATION
GROUP BY LEN(CITY)
ORDER BY LEN(CITY) DESC;
