/* MySQL */

SELECT PARENT.N
    , CASE
        WHEN PARENT.P IS NULL THEN 'Root'
        WHEN MIN(ISNULL(CHILD.N)) = 0 THEN 'Inner' -- has child
        ELSE 'Leaf'
    END
FROM BST AS PARENT
LEFT OUTER JOIN BST AS CHILD ON PARENT.N = CHILD.P
GROUP BY PARENT.N, PARENT.P
